
winget install --id=Google.Chrome -e  --scope "machine" 
&& winget install --id=Mozilla.Firefox -e  --scope "machine" 
&& winget install --id=GeoGebra.Classic -e  --scope "machine" 
&& winget install --id=Google.EarthPro -e  --scope "machine" 
&& winget install --id=IrfanSkiljan.IrfanView -e  --scope "machine" 
&& winget install --id=Notepad++.Notepad++ -e  --scope "machine" 
&& winget install --id=dotPDN.PaintDotNet -e  --scope "machine" 
&& winget install --id=VideoLAN.VLC -e  --scope "machine" 
&& winget install --id=Adobe.Acrobat.Reader.64-bit -e  --scope "machine" 
&& winget install --id=Oracle.JavaRuntimeEnvironment -e  --scope "machine" 
&& winget install --id=Adobe.CreativeCloud -e  --scope "machine" 
&& winget install --id=Microsoft.AppInstaller -e  --scope "machine"